### ISSUE TITLE
lock/unlock

### ISSUE THREAD

**Issue by pradeepnarava** [maisi/M365-Power#3]
Hi,
how can we lock/unlock m365 using this app?
If there is no code then how can I implement it,any idea? .

**Comment by lululombard** [comment]
It's in the todo

**Comment by pradeepnarava** [comment]
Is there any code I can do to fix it or any other who can help me with it.

**Comment by pradeepnarava** [comment]
Can you please reply asap.I will be thankful if you can help with it.

**Comment by lululombard** [comment]
That's not my project, I don't really know. Sorry :/

**Comment by pradeepnarava** [comment]
Who is the author ?Can I know please..

**Comment by maisi** [comment]
Hello,
locking and a few other scooter features aren't implemented yet (like rear light switch, cruise mode switch, break strength) because I don't really use them, but it shouldn't be too much work so I'll try to implement it tonight or tomorrow.

**Comment by pradeepnarava** [comment]
Thank you very much,I will wait for it.I highly appreciate your work.

**Comment by maisi** [comment]
Just did a quick implementation of the locking. Worked for me, I hope it does for you too.
[app-debug.zip](https://github.com/maisi/M365-Power/files/2276299/app-debug.zip)

**Comment by pradeepnarava** [comment]
Thankyou very much,let me try,will get back to you again.

**Comment by pradeepnarava** [comment]
Hi,
Thankyou very much for lock/unlock.
The problem here is I got connected ,locked the scooter,closed the app,now scooter is not detectable at all and I cant go into it,tried to SCAN but its not detecting anymore, i guess because its in locked state,how can I unlock now ?

Thankyou once again for lock/unlock feauture.

**Comment by maisi** [comment]
The scooter will be detected when it's locked, probably the locking just didn't work and it's turned off. When you move the scooter, does it break and make sounds ?
Currently the locking switch (and the others) only work when the handler has been started before. 
I might have to change that since it's a little counter-intuitive. 

Lastest version:
[app-debug-1.zip](https://github.com/maisi/M365-Power/files/2277458/app-debug-1.zip)

**Comment by pradeepnarava** [comment]
Hi Maisi,
I found that your code is not scanning any devices anymore from few hrs back,any reason ?

**Comment by pradeepnarava** [comment]
Its due to location off,solved,tq.

**Comment by pradeepnarava** [comment]
Is there a way to control front light on/off?

**Comment by maisi** [comment]
No, it's only controllable with the button as far as I know.
